// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportActivityTracking.Domain.Data;

#nullable disable

namespace SportActivityTracking.Domain.Migrations
{
    [DbContext(typeof(ActividadDeportivaContext))]
    partial class ActividadDeportivaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportActivityTracking.Domain.Entities.ActividadDeportiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoDeporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActividadesDeportivas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Carrera matutina en el parque",
                            DuracionMinutos = 45,
                            Fecha = new DateTime(2025, 3, 24, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Running",
                            Usuario = "Franyeli@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Sesión de natación",
                            DuracionMinutos = 60,
                            Fecha = new DateTime(2025, 3, 23, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Natación",
                            Usuario = "Franklin@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Partido de fútbol",
                            DuracionMinutos = 90,
                            Fecha = new DateTime(2025, 3, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Fútbol",
                            Usuario = "pedro@hotmail.com"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Clases de yoga en casa",
                            DuracionMinutos = 30,
                            Fecha = new DateTime(2025, 3, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Yoga",
                            Usuario = "luisafernandez@outlook.com"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Entrenamiento de fuerza en el gimnasio",
                            DuracionMinutos = 50,
                            Fecha = new DateTime(2025, 3, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Gimnasio",
                            Usuario = "carlosm@gmail.com"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Ruta en bicicleta por la montaña",
                            DuracionMinutos = 120,
                            Fecha = new DateTime(2025, 3, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Ciclismo",
                            Usuario = "sofiaj@yahoo.com"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Partido de baloncesto con amigos",
                            DuracionMinutos = 60,
                            Fecha = new DateTime(2025, 3, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoDeporte = "Baloncesto",
                            Usuario = "daniel@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
